In [446]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"C:\Users\Sadit\Downloads\Ames_Housing_Sales.csv")

df.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,Alley,BedroomAbvGr,BldgType,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,...,ScreenPorch,Street,TotRmsAbvGrd,TotalBsmtSF,Utilities,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold,SalePrice
0,856.0,854.0,0.0,NaN,3,1Fam,TA,No,706.0,0.0,...,0.0,Pave,8,856.0,AllPub,0.0,2003,2003,2008,208500.0
1,1262.0,0.0,0.0,NaN,3,1Fam,TA,Gd,978.0,0.0,...,0.0,Pave,6,1262.0,AllPub,298.0,1976,1976,2007,181500.0
2,920.0,866.0,0.0,NaN,3,1Fam,TA,Mn,486.0,0.0,...,0.0,Pave,6,920.0,AllPub,0.0,2001,2002,2008,223500.0
3,961.0,756.0,0.0,NaN,3,1Fam,Gd,No,216.0,0.0,...,0.0,Pave,7,756.0,AllPub,0.0,1915,1970,2006,140000.0
4,1145.0,1053.0,0.0,NaN,4,1Fam,TA,Av,655.0,0.0,...,0.0,Pave,9,1145.0,AllPub,192.0,2000,2000,2008,250000.0

In [447]:
df.describe()

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,BsmtUnfSF,EnclosedPorch,...,OverallQual,PoolArea,ScreenPorch,TotRmsAbvGrd,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold,SalePrice
count,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,...,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.000000,1379.00000
mean,1177.129804,353.424946,3.609862,2.865120,455.578680,48.102248,0.430747,0.058738,570.765047,21.039159,...,6.187092,2.920957,15.945613,6.552574,1074.445975,97.456853,1972.958666,1985.435098,2007.812183,185479.51124
std,387.014961,439.553171,30.154682,0.783961,459.691379,164.324665,0.514052,0.238285,443.677845,60.535107,...,1.345780,41.335545,57.249593,1.589821,436.371874,126.699192,29.379883,20.444852,1.330221,79023.89060
min,438.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1880.000000,1950.000000,2006.000000,35311.00000
25%,894.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,228.000000,0.000000,...,5.000000,0.000000,0.000000,5.000000,810.000000,0.000000,1955.000000,1968.000000,2007.000000,134000.00000
50%,1098.000000,0.000000,0.000000,3.000000,400.000000,0.000000,0.000000,0.000000,476.000000,0.000000,...,6.000000,0.000000,0.000000,6.000000,1008.000000,0.000000,1976.000000,1994.000000,2008.000000,167500.00000
75%,1414.000000,738.500000,0.000000,3.000000,732.000000,0.000000,1.000000,0.000000,811.000000,0.000000,...,7.000000,0.000000,0.000000,7.000000,1314.000000,171.000000,2001.000000,2004.000000,2009.000000,217750.00000
max,4692.000000,2065.000000,508.000000,6.000000,5644.000000,1474.000000,2.000000,2.000000,2336.000000,552.000000,...,10.000000,738.000000,480.000000,12.000000,6110.000000,857.000000,2010.000000,2010.000000,2010.000000,755000.00000

In [448]:
numeric_df = df.select_dtypes(include=['float64', 'int64'])

correlations = numeric_df.corr()['SalePrice']

selected_features = correlations[abs(correlations) > 0.2].index.tolist()

data=df[selected_features]
data.head()

,1stFlrSF,2ndFlrSF,BsmtFinSF1,BsmtFullBath,BsmtUnfSF,Fireplaces,FullBath,GarageArea,GarageCars,GarageYrBlt,...,LotFrontage,MasVnrArea,OpenPorchSF,OverallQual,TotRmsAbvGrd,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd,SalePrice
0,856.0,854.0,706.0,1,150.0,0,2,548.0,2,2003.0,...,65.0,196.0,61.0,7,8,856.0,0.0,2003,2003,208500.0
1,1262.0,0.0,978.0,0,284.0,1,2,460.0,2,1976.0,...,80.0,0.0,0.0,6,6,1262.0,298.0,1976,1976,181500.0
2,920.0,866.0,486.0,1,434.0,1,2,608.0,2,2001.0,...,68.0,162.0,42.0,7,6,920.0,0.0,2001,2002,223500.0
3,961.0,756.0,216.0,1,540.0,1,1,642.0,3,1998.0,...,60.0,0.0,35.0,7,7,756.0,0.0,1915,1970,140000.0
4,1145.0,1053.0,655.0,1,490.0,1,2,836.0,3,2000.0,...,84.0,350.0,84.0,8,9,1145.0,192.0,2000,2000,250000.0

In [449]:
cat=df.select_dtypes(include='string')
print(cat)

     Alley BldgType BsmtCond BsmtExposure BsmtFinType1 BsmtFinType2 BsmtQual  \
0      NaN     1Fam       TA           No          GLQ          Unf       Gd
1      NaN     1Fam       TA           Gd          ALQ          Unf       Gd
2      NaN     1Fam       TA           Mn          GLQ          Unf       Gd
3      NaN     1Fam       Gd           No          ALQ          Unf       TA
4      NaN     1Fam       TA           Av          GLQ          Unf       Gd
...    ...      ...      ...          ...          ...          ...      ...
1374   NaN     1Fam      NaN          NaN          NaN          NaN      NaN
1375   NaN     1Fam       TA           No          ALQ          Rec       Gd
1376   NaN     1Fam       Gd           No          GLQ          Unf       TA
1377   NaN     1Fam       TA           Mn          GLQ          Rec       TA
1378   NaN     1Fam       TA           No          BLQ          LwQ       TA

     CentralAir Condition1 Condition2  ... MiscFeature Neighborhood  \
0             Y       Norm       Norm  ...         NaN      CollgCr
1             Y      Feedr       Norm  ...         NaN      Veenker
2             Y       Norm       Norm  ...         NaN      CollgCr
3             Y       Norm       Norm  ...         NaN      Crawfor
4             Y       Norm       Norm  ...         NaN      NoRidge
...         ...        ...        ...  ...         ...          ...
1374          Y       Norm       Norm  ...         NaN      Gilbert
1375          Y       Norm       Norm  ...         NaN       NWAmes
1376          Y       Norm       Norm  ...        Shed      Crawfor
1377          Y       Norm       Norm  ...         NaN        NAmes
1378          Y       Norm       Norm  ...         NaN      Edwards

     PavedDrive PoolQC RoofMatl RoofStyle SaleCondition SaleType Street  \
0             Y    NaN  CompShg     Gable        Normal       WD   Pave
1             Y    NaN  CompShg     Gable        Normal       WD   Pave
2             Y    NaN  CompShg     Gable        Normal       WD   Pave
3             Y    NaN  CompShg     Gable       Abnorml       WD   Pave
4             Y    NaN  CompShg     Gable        Normal       WD   Pave
...         ...    ...      ...       ...           ...      ...    ...
1374          Y    NaN  CompShg     Gable        Normal       WD   Pave
1375          Y    NaN  CompShg     Gable        Normal       WD   Pave
1376          Y    NaN  CompShg     Gable        Normal       WD   Pave
1377          Y    NaN  CompShg       Hip        Normal       WD   Pave
1378          Y    NaN  CompShg     Gable        Normal       WD   Pave

     Utilities
0       AllPub
1       AllPub
2       AllPub
3       AllPub
4       AllPub
...        ...
1374    AllPub
1375    AllPub
1376    AllPub
1377    AllPub
1378    AllPub

[1379 rows x 43 columns]

In [450]:
print(df['BldgType'].unique())

<StringArray>
['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs']
Length: 5, dtype: str

In [451]:
alley_dummies = pd.get_dummies(df['Alley'], prefix='A')
df = pd.concat([df, alley_dummies], axis=1)

data['BldgType'] = df['BldgType'].map({
    '1Fam': 1,
    '2fmCon': 2,
    'Duplex': 3,
    'TwnhsE': 4,
    'Twnhs': 5
})
data['LotShape'] = df['LotShape'].map({
    'Reg': 4,
    'IR1': 3,
    'IR2': 2,
    'IR3': 1
})
data['LotConfig'] = df['LotConfig'].map({
    'Inside': 1,
    'Corner': 2,
    'CulDSac': 3,
    'FR2': 4,
    'FR3': 5
})
data['LandContour'] = df['LandContour'].map({
    'Lvl': 3,
    'Bnk': 2,
    'HLS': 1,
    'Low': 0
})
data['LandSlope'] = df['LandSlope'].map({
    'Gtl': 3,
    'Mod': 2,
    'Sev': 1
})

roofstyle_dummies = pd.get_dummies(df['RoofStyle'], prefix='RoofStyle')
data = pd.concat([data, roofstyle_dummies], axis=1)

data['ExterQual'] = df['ExterQual'].map({
    'Ex': 4,
    'Gd': 3,
    'TA': 2,
    'Fa': 1,
    'Po': 0
})
data['ExterCond'] = df['ExterCond'].map({
    'Ex': 4,
    'Gd': 3,
    'TA': 2,
    'Fa': 1,
    'Po': 0
})
data['BsmtQual'] = df['BsmtQual'].map({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1
}).fillna(0)
data['BsmtCond'] = df['BsmtCond'].map({
    'Ex': 4,
    'Gd': 3,
    'TA': 2,
    'Fa': 1,
    'Po': 0
}).fillna(0)

data.head()

,1stFlrSF,2ndFlrSF,BsmtFinSF1,BsmtFullBath,BsmtUnfSF,Fireplaces,FullBath,GarageArea,GarageCars,GarageYrBlt,...,RoofStyle_Flat,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,ExterQual,ExterCond,BsmtQual,BsmtCond
0,856.0,854.0,706.0,1,150.0,0,2,548.0,2,2003.0,...,False,True,False,False,False,False,3,2,4.0,2.0
1,1262.0,0.0,978.0,0,284.0,1,2,460.0,2,1976.0,...,False,True,False,False,False,False,2,2,4.0,2.0
2,920.0,866.0,486.0,1,434.0,1,2,608.0,2,2001.0,...,False,True,False,False,False,False,3,2,4.0,2.0
3,961.0,756.0,216.0,1,540.0,1,1,642.0,3,1998.0,...,False,True,False,False,False,False,2,2,3.0,3.0
4,1145.0,1053.0,655.0,1,490.0,1,2,836.0,3,2000.0,...,False,True,False,False,False,False,3,2,4.0,2.0

In [452]:
finalcor = data.corr()['SalePrice'].drop('SalePrice')
finalcor = finalcor[abs(finalcor) > 0.5]

selected_columns = finalcor.index.tolist()

data = data[selected_columns]
data['SalePrice']=df['SalePrice']
data.head()

,1stFlrSF,FullBath,GarageArea,GarageCars,GrLivArea,OverallQual,TotRmsAbvGrd,TotalBsmtSF,YearBuilt,YearRemodAdd,ExterQual,SalePrice
0,856.0,2,548.0,2,1710.0,7,8,856.0,2003,2003,3,208500.0
1,1262.0,2,460.0,2,1262.0,6,6,1262.0,1976,1976,2,181500.0
2,920.0,2,608.0,2,1786.0,7,6,920.0,2001,2002,3,223500.0
3,961.0,1,642.0,3,1717.0,7,7,756.0,1915,1970,2,140000.0
4,1145.0,2,836.0,3,2198.0,8,9,1145.0,2000,2000,3,250000.0

In [453]:
Q1=data.quantile(0.25)
Q3=data.quantile(0.75)

IQR=Q3-Q1

lower=Q1-IQR*6.0
upper=Q1+IQR*6.0

data=data[(data>lower) & (data<upper)]
print(len(df))

1379

In [ ]:
data['SalePrice'] = data['SalePrice'].fillna(data['SalePrice'].mean())
data = data.fillna(data.mode().iloc[0])

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler

X = data.drop(['SalePrice'], axis=1)
scaler = StandardScaler()
X = scaler.fit_transform(X)

Y = data['SalePrice']

score = []

limit = int(len(data) ** 0.5)

for i in range(1, limit,2):
    model = KNeighborsRegressor(n_neighbors=i,weights='distance')
    eval_scores = cross_val_score(model, X, Y, cv=5)
    score.append([i, eval_scores.mean()])

bestK = max(score, key=lambda x: x[1])[0]
bestS=max(score,key=lambda x :x[1])[1]
print(bestK)
print(bestS)

9
0.8186037503524801

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=69)


finalModel = KNeighborsRegressor(n_neighbors=bestK,weights='distance')
finalModel.fit(X_train,Y_train)


print(f"Model: KNN with k={bestK}")
print(f"Training R²: {finalModel.score(X_test, Y_test):.4f}")

Model: KNN with k=9
Training R²: 0.8196

In [457]:
import joblib
joblib.dump(finalModel, 'house_price_knn.pkl')

['house_price_knn.pkl']